### ISSUE TITLE
assert in TLS_OUT_OF_INDEXES

### ISSUE THREAD

**Issue by revelator** [lhmouse/mcfgthread#20] opened 2017-01-28 16:19 UTC
Not sure if anyone had this before, but atleast it seems to affect atleast a few programs that use mcf vtk seems to dont like it at all and will throw this on exit 100% of the time.

**Comment by lhmouse** [comment] 2017-01-29 07:18
This could be caused by use of thread local storage after the mcfgthread DLL is unloaded, probably inside a callback registered using the `atexit()` function from mingw-w64. They don't use the MSVCRT one. Rather, their exit callbacks are called when MSVCRT.DLL is unloaded, at which point mcfgthread.dll would no longer be available. A possible workaround is, not freeing the TLS index if the process is exiting (this can be observed from the `lpReserved` parameter of the `DllMain()` function. However a 'real' fix would be reimplementing the `atexit()` function inside mcfgthread (see src/pre/module.h) and replacing the mingw-w64 one. Unfortunately I am on vacation these days. We need further discussion about this issue a few days later.

**Comment by revelator** [comment] 2017-01-29 19:56
That would be nice :), and a happy vacation time to you.

**Comment by lhmouse** [comment] 2017-02-02 06:04
I am at the airport and don't have standard documents at hand at the moment. But IIRC, the C standard merely copies the `tss_create()` from POSIX (without its name copied of course) and says nothing about what would happen should `exit()` be called, while the C++ standard requires thread-local objects of _the thread that calls `exit()`_ be destroyed before any other static, non-thread local objects, and in a footnote it also says the implementation-specific thread manager (I really hate this word!) is allowed to be a plain static object. In my opinion, in the C++ case TLS should not be considered available during exit callbacks and destruction of any static objects. Any access to TLS should fail in this scenario.

**Comment by lhmouse** [comment] 2017-02-02 12:09
## ISO/IEC WG21 N4618
### 3.6.4 Termination [basic.start.term]
4. If there is a use of a standard library object or function not permitted within signal handlers (18.10) that
does not happen before (1.10) completion of destruction of objects with static storage duration and execution
of std::atexit registered functions (18.5), the program has undefined behavior. [ Note: If there is a use of
an object with static storage duration that does not happen before the object’s destruction, the program
has undefined behavior. Terminating every thread before a call to std::exit or the exit from main is
sufficient, but not necessary, to satisfy these requirements. These requirements permit thread managers as
static-storage-duration objects. — end note ]

**Comment by lhmouse** [comment] 2017-02-02 12:10
## ISO/IEC WG21 N4618
### 3.6.4 Termination [basic.start.term]
4. If there is a use of a standard library object or function not permitted within signal handlers (18.10) that does not happen before (1.10) completion of destruction of objects with static storage duration and execution of std::atexit registered functions (18.5), the program has undefined behavior. [ Note: If there is a use of an object with static storage duration that does not happen before the object’s destruction, the program has undefined behavior. Terminating every thread before a call to std::exit or the exit from main is sufficient, but not necessary, to satisfy these requirements. These requirements permit thread managers as static-storage-duration objects. — end note ]

**Comment by lhmouse** [comment] 2017-02-02 14:15
Note that removal of the assertion probably would not fix this problem. Please test.

**Comment by lhmouse** [comment] 2017-02-02 14:26
[libgcc ignores the value of `__gthread_setspecific()`](https://gcc.gnu.org/viewcvs/gcc/trunk/libgcc/emutls.c?view=markup#l163), which could result in memory leaks, but it would not trigger the referenced assertion failure any more.

**Comment by revelator** [comment] 2017-02-05 22:01
Seems to have fixed it in vtk but now qt5 crashes Oo.

**Comment by lhmouse** [comment] 2017-02-06 01:51
What does gdb say?

**Comment by revelator** [comment] 2017-02-06 05:41
Not built with debugging symbols, but ill give it a try hang on.

**Comment by revelator** [comment] 2017-02-09 03:32
Hmm ok not really helpfull gdb cannot show anything usefull, just that it throws a segmentation fault when creating a thread. Error is something like Thread 9908.0x3308 some base address in ?? ()
Guess ill need to rebuild it with debugging symbols if i want it to show something usefull.

**Comment by lhmouse** [comment] 2017-02-09 04:51
> Hmm ok not really helpfull gdb cannot show anything usefull, just that it throws a segmentation fault when creating a thread. Error is something like Thread 9908.0x3308 some base address in ?? ()

A full backtrace could be helpful.

**Comment by revelator** [comment] 2017-02-09 05:24
ill see what i can do :) 

Btw the thread crashes in wfvprintf function it seems if that is any help.

**Comment by lhmouse** [comment] 2017-02-09 06:54
> Btw the thread crashes in wfvprintf function it seems if that is any help.

Probably it has something to do with thread-local locale objects. Not sure.

**Comment by revelator** [comment] 2017-02-09 07:28
might be related to the lenght of the printf buffer string, i recall from working on the quake engine that we had to remove the function for printing OpenGL abilities because later drivers crashed when it was enabled. Reason i think it might be related is that the crash only seems to affect gui applications, the console applications work fine.

**Comment by lhmouse** [comment] 2017-02-09 08:10
If you think mcfgthread is the cause you can set two break points on `_MCFCRT_TlsGet()` and `_MCFCRT_TlsRequire()` and see whether they are hit just before the crash. The former is called from `__gthread_getspecific()` and the later is called from `__gthread_setspecific()`.

**Comment by revelator** [comment] 2017-02-09 08:42
Tbh im not sure, depends if mcfgthread uses specific api printing. The 
bug mentioned earlier only affectedgfx drivers because the printed 
strings got to long for the buffer to hold, yeah opengl is quite a mess 
because it still retains compatibility with older deprecated functions. 
In a way thats great to but by maintaining all of them the khronos group 
kinda dug their own graves because many older sources would simply no 
longer run because of said bug, and many old games no longer have 
accessible source code so its impossible to fix unless you know your way 
around a hex editor.


Den 09-02-2017 kl. 09:10 skrev LH_Mouse:

**Comment by lhmouse** [comment] 2017-02-09 08:51
At the moment the only function in which mcfghtread does print something to standard streams is the `_MCFCRT_Bail()` function, which uses `WriteConsoleW()` to do that. This function is however used almost everywhere indirectly by the `_MCFCRT_ASSERT()` and `_MCFCRT_ASSERT_MSG()` macros if the standard macro `NDEBUG` is **not** defined.

**Comment by lhmouse** [comment] 2017-02-09 08:56
I am afraid that stdio functions from MinGW-w64 do use thread local storage internally. This should only matter if both conditions are true:
1. The TLS is accessed via mcfgthread, i.e. using `__thread` and not from MSVCRT whatsoever.
2. The functions in question are linked statically (at the moment this is the case).

**Comment by revelator** [comment] 2017-02-09 14:02
Hmm the bug in question only happens on the statically built qt5, 
strangely enough it worked on previous mcfgthread builds, so the 
question is did we unintentionally break something while trying to fix 
the TLS index assert previously ? or did more changes to the code take 
place in the meantime.


Den 09-02-2017 kl. 09:56 skrev LH_Mouse:

**Comment by lhmouse** [comment] 2017-02-09 16:31
There haven't be many commits this year.

**Comment by lhmouse** [comment] 2017-02-09 16:33
There haven't be many commits since the beginning of this year. Maybe you can try older versions and see whether they crash. I have been uploading binary builds with commits so they are available in the git history.
<https://github.com/lhmouse/mcfgthread/commits/master>

**Comment by revelator** [comment] 2017-02-09 17:54
Did not notice much either besides the work done recently for the 
assertion problem, but kinda hard to believe that it would cause a crash 
in the printf buffers Oo that is why i asked. Hmm QT5 is a rather long 
build but i noticed fox toolkit also crashes now so ill try a debug 
build of that one, maybe we can get some answers as to why this happens.


Den 09-02-2017 kl. 17:33 skrev LH_Mouse:

**Comment by lhmouse** [comment] 2017-02-10 14:28
Before this commit use of destroyed TLS control would result in a crash, while now it fails silently. I don't think it is the cause either.

**Comment by lhmouse** [comment] 2017-03-26 11:28
I am closing this issue as the problem mentioned in the topic is gone. Please open a new issue for the remaining part of it.

**Closed by lhmouse** 2017-03-26 11:28 UTC
Labels: category:bug-normal, status:resolved-fixed

**Comment by revelator** [comment] 2017-03-27 07:44
Yep should be ok now. Thanks for the fix.

Ralph Engels

2017-03-26 13:28 GMT+02:00 LH_Mouse <notifications@github.com>:
